# Generated by Django 4.1.6 on 2023-03-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('pass_word', models.CharField(max_length=64)),
                ('fname', models.CharField(max_length=64)),
                ('mname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('mob_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
